# This file is auto-generated. Please DO NOT edit.
# To update this file, add your prebuilts to the vendor_prebuilt folder
# and call ./setup-makefiles-local.sh
PRODUCT_COPY_FILES += \
$(LOCAL_PATH)/vendor_prebuilt/bin/glgps:system/bin/glgps \
$(LOCAL_PATH)/vendor_prebuilt/bin/sensors-config:system/bin/sensors-config \
$(LOCAL_PATH)/vendor_prebuilt/bin/wifimacwriter:system/bin/wifimacwriter \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/bcm4329.hcd:system/etc/firmware/bcm4329.hcd \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_reference.axf:system/etc/firmware/nvmm_reference.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_sorensondec.axf:system/etc/firmware/nvmm_sorensondec.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_vc1dec.axf:system/etc/firmware/nvmm_vc1dec.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_wmadec.axf:system/etc/firmware/nvmm_wmadec.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvmm_wmaprodec.axf:system/etc/firmware/nvmm_wmaprodec.axf \
$(LOCAL_PATH)/vendor_prebuilt/etc/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
$(LOCAL_PATH)/vendor_prebuilt/etc/nvram.txt:system/etc/nvram.txt \
$(LOCAL_PATH)/vendor_prebuilt/etc/nvram_murata.txt:system/etc/nvram_murata.txt \
$(LOCAL_PATH)/vendor_prebuilt/etc/nvram_nh615.txt:system/etc/nvram_nh615.txt \
$(LOCAL_PATH)/vendor_prebuilt/etc/nvram_nh615_sl101.txt:system/etc/nvram_nh615_sl101.txt \
$(LOCAL_PATH)/vendor_prebuilt/lib/egl/libEGL_perfhud.so:system/lib/egl/libEGL_perfhud.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/egl/libGLESv1_CM_perfhud.so:system/lib/egl/libGLESv1_CM_perfhud.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/egl/libGLESv2_perfhud.so:system/lib/egl/libGLESv2_perfhud.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/hw/camera.tegra.so:system/lib/hw/camera.tegra.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/hw/gps.ventana.so:system/lib/hw/gps.ventana.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/hw/lights.ventana.so:system/lib/hw/lights.ventana.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/hw/sensors.ventana.so:system/lib/hw/sensors.ventana.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libcgdrv.so:system/lib/libcgdrv.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libmllite.so:system/lib/libmllite.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libmlplatform.so:system/lib/libmlplatform.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libmpl.so:system/lib/libmpl.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvavp.so:system/lib/libnvavp.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvcpud.so:system/lib/libnvcpud.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvcpud_client.so:system/lib/libnvcpud_client.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvhdmi3dplay_jni.so:system/lib/libnvhdmi3dplay_jni.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm.so:system/lib/libnvmm.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_asfparser.so:system/lib/libnvmm_asfparser.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_aviparser.so:system/lib/libnvmm_aviparser.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_msaudio.so:system/lib/libnvmm_msaudio.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_vc1_video.so:system/lib/libnvmm_vc1_video.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_vp6_video.so:system/lib/libnvmm_vp6_video.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvomx.so:system/lib/libnvomx.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvos.so:system/lib/libnvos.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvparser.so:system/lib/libnvparser.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvrm.so:system/lib/libnvrm.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvsm.so:system/lib/libnvsm.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvsystemuiext_jni.so:system/lib/libnvsystemuiext_jni.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvtestio.so:system/lib/libnvtestio.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvtestresults.so:system/lib/libnvtestresults.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libnvwsi.so:system/lib/libnvwsi.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libsensors.al3000a.so:system/lib/libsensors.al3000a.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libsensors.base.so:system/lib/libsensors.base.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libsensors.isl29018.so:system/lib/libsensors.isl29018.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libsensors.mpl.so:system/lib/libsensors.mpl.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
$(LOCAL_PATH)/vendor_prebuilt/lib/modules/battery_rvsd.ko:system/lib/modules/battery_rvsd.ko \
$(LOCAL_PATH)/vendor_prebuilt/lib/modules/scsi_wait_scan.ko:system/lib/modules/scsi_wait_scan.ko \
